# Notes
# - cannot run on Windows, as we use shell scripts

name: "Release"

on:
  push:
    branches:
      - 'release-*'

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  HELIDON_PIPELINES: 'true'
  MAVEN_HTTP_ARGS: '-Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3'

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-validate-workflow:
    uses: ./.github/workflows/validate.yml
  release:
    needs: call-validate-workflow
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Release
        env:
          GPG_PASSPHRASE: ${{ secrets.HELIDON_GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.HELIDON_GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.HELIDON_GPG_PUBLIC_KEY }}
          MAVEN_SETTINGS_FILE: ${{ secrets.MAVEN_SETTINGS }}
        run: |
          git config user.email "helidon-robot_ww@oracle.com"
          git config user.name "Helidon Robot"
          etc/scripts/release.sh release_build
